# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy Contentful App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies and build
      run: |
        npm ci
        npm run build
      working-directory: path/to/your/app

    - name: Bundle Contentful App
      run: |
        npx @contentful/app-scripts bundle --directory /home/runner/work/contentful/contentful
      working-directory: path/to/your/app

    - name: Deploy Contentful App
      uses: contentful/actions-app-deploy@v1
      with:
        organization-id: ${{ secrets.CONTENTFUL_ORG_ID }}
        app-definition-id: ${{ secrets.APP_DEFINITION_ID }}
        access-token: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
        bundle-dir: /home/runner/work/contentful/contentful


    
       
   
    
